---
swagger: "2.0"
info:
  version: "2018-12-28T14:04:24Z"
  title: "development-releases-notifier"
host: "szo785eyq6.execute-api.us-east-1.amazonaws.com"
basePath: "/development"
schemes:
- "https"
paths:
  /github:
    post:
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        422:
          description: "422 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: "500 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        401:
          description: "401 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        502:
          description: "502 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        403:
          description: "403 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        404:
          description: "404 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        504:
          description: "504 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
